# Generated by Django 6.0.1 on 2026-02-01 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.PositiveIntegerField()),
                ('destination_port', models.PositiveIntegerField()),
                ('protocol', models.CharField(max_length=20)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('packets_sent', models.PositiveIntegerField(default=0)),
                ('packets_received', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'traffic_flow',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['source_ip', 'destination_ip'], name='traffic_flo_source__0fbfb9_idx'), models.Index(fields=['protocol', 'start_time'], name='traffic_flo_protoco_84f225_idx'), models.Index(fields=['is_active', 'start_time'], name='traffic_flo_is_acti_92d320_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('interface_name', models.CharField(db_index=True, max_length=100)),
                ('metric_type', models.CharField(choices=[('bandwidth_utilization', 'Bandwidth Utilization'), ('packet_loss_rate', 'Packet Loss Rate'), ('latency', 'Network Latency'), ('throughput', 'Network Throughput'), ('connection_count', 'Active Connections')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('protocol', models.CharField(blank=True, max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'traffic_metric',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['interface_name', 'metric_type', 'timestamp'], name='traffic_met_interfa_f2b4e7_idx'), models.Index(fields=['protocol', 'timestamp'], name='traffic_met_protoco_b0d52c_idx')],
            },
        ),
    ]
