# Generated by Django 6.0.1 on 2026-02-01 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkBandwidthTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('test_server', models.CharField(max_length=255)),
                ('test_type', models.CharField(choices=[('download', 'Download'), ('upload', 'Upload'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('bandwidth_mbps', models.FloatField(help_text='Bandwidth in Mbps')),
                ('data_transferred_mb', models.FloatField(help_text='Data transferred in MB')),
                ('test_duration_seconds', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'network_bandwidth_test',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['test_server', 'test_type', 'timestamp'], name='network_ban_test_se_e1a81a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_address', models.GenericIPAddressField()),
                ('local_port', models.PositiveIntegerField()),
                ('remote_address', models.GenericIPAddressField()),
                ('remote_port', models.PositiveIntegerField()),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP')], max_length=10)),
                ('state', models.CharField(choices=[('ESTABLISHED', 'Established'), ('LISTEN', 'Listen'), ('TIME_WAIT', 'Time Wait'), ('CLOSE_WAIT', 'Close Wait'), ('SYN_SENT', 'SYN Sent'), ('SYN_RECV', 'SYN Received'), ('CLOSED', 'Closed')], max_length=20)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('process_name', models.CharField(blank=True, max_length=255)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('established_at', models.DateTimeField()),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'network_connection',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['protocol', 'state'], name='network_con_protoco_e308f9_idx'), models.Index(fields=['local_address', 'local_port'], name='network_con_local_a_474277_idx'), models.Index(fields=['remote_address', 'remote_port'], name='network_con_remote__3c806b_idx'), models.Index(fields=['is_active', 'last_activity'], name='network_con_is_acti_84ce3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('interface_type', models.CharField(choices=[('ethernet', 'Ethernet'), ('wifi', 'WiFi'), ('loopback', 'Loopback'), ('vpn', 'VPN'), ('bridge', 'Bridge'), ('virtual', 'Virtual')], max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subnet_mask', models.GenericIPAddressField(blank=True, null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('mtu', models.PositiveIntegerField(blank=True, null=True)),
                ('speed_mbps', models.PositiveIntegerField(blank=True, help_text='Interface speed in Mbps', null=True)),
                ('is_up', models.BooleanField(default=True)),
                ('is_monitored', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'network_interface',
                'indexes': [models.Index(fields=['interface_type', 'is_monitored'], name='network_int_interfa_08ce66_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkLatencyTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_host', models.CharField(db_index=True, max_length=255)),
                ('target_ip', models.GenericIPAddressField()),
                ('test_type', models.CharField(choices=[('ping', 'ICMP Ping'), ('tcp_connect', 'TCP Connect'), ('http_get', 'HTTP GET'), ('dns_lookup', 'DNS Lookup')], max_length=20)),
                ('latency_ms', models.FloatField(help_text='Latency in milliseconds')),
                ('packet_loss_percent', models.FloatField(default=0.0)),
                ('jitter_ms', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('test_duration_ms', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'network_latency_test',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_host', 'test_type', 'timestamp'], name='network_lat_target__32c516_idx'), models.Index(fields=['success', 'timestamp'], name='network_lat_success_0a621f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkMetricData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('metric_type', models.CharField(choices=[('bytes_sent', 'Bytes Sent'), ('bytes_received', 'Bytes Received'), ('packets_sent', 'Packets Sent'), ('packets_received', 'Packets Received'), ('errors_in', 'Input Errors'), ('errors_out', 'Output Errors'), ('drops_in', 'Input Drops'), ('drops_out', 'Output Drops'), ('bandwidth_utilization', 'Bandwidth Utilization'), ('latency', 'Network Latency'), ('jitter', 'Network Jitter'), ('packet_loss', 'Packet Loss')], max_length=50)),
                ('value', models.BigIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='netmetrics.networkinterface')),
            ],
            options={
                'db_table': 'network_metric_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['interface', 'metric_name', 'timestamp'], name='network_met_interfa_5f5cb4_idx'), models.Index(fields=['metric_type', 'direction', 'timestamp'], name='network_met_metric__a75db3_idx')],
            },
        ),
    ]
