# Generated by Django 6.0.1 on 2026-02-01 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('incident_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('detection_time_ms', models.PositiveIntegerField(help_text='Time to detect the incident')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Time to respond', null=True)),
                ('resolution_time_ms', models.PositiveIntegerField(blank=True, help_text='Time to resolve', null=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('target_resource', models.CharField(max_length=255)),
                ('attack_vector', models.CharField(blank=True, max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'security_incident',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['incident_type', 'severity'], name='security_in_inciden_bcd277_idx'), models.Index(fields=['is_resolved', 'timestamp'], name='security_in_is_reso_bda9f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('metric_type', models.CharField(choices=[('threat_detection_time', 'Threat Detection Time'), ('vulnerability_scan_time', 'Vulnerability Scan Time'), ('security_alert_response_time', 'Security Alert Response Time'), ('firewall_rule_processing_time', 'Firewall Rule Processing Time'), ('intrusion_detection_latency', 'Intrusion Detection Latency')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_resource', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'security_metric',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'severity', 'timestamp'], name='security_me_metric__4450f5_idx')],
            },
        ),
    ]
