# Generated by Django 6.0.1 on 2026-02-01 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('is_running', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'application_instance',
                'indexes': [models.Index(fields=['name', 'environment'], name='application_name_7f308a_idx'), models.Index(fields=['is_running', 'last_heartbeat'], name='application_is_runn_b1b999_idx')],
                'unique_together': {('name', 'host', 'port')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('histogram_name', models.CharField(db_index=True, max_length=255)),
                ('bucket_boundaries', models.JSONField(help_text='List of bucket boundaries')),
                ('bucket_counts', models.JSONField(help_text='Count for each bucket')),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('sum_value', models.FloatField(default=0.0)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histograms', to='appmetrics.applicationinstance')),
            ],
            options={
                'db_table': 'application_histogram',
                'indexes': [models.Index(fields=['instance', 'histogram_name'], name='application_instanc_c9725d_idx')],
                'unique_together': {('instance', 'histogram_name')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationGauge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gauge_name', models.CharField(db_index=True, max_length=255)),
                ('current_value', models.FloatField()),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='appmetrics.applicationinstance')),
            ],
            options={
                'db_table': 'application_gauge',
                'indexes': [models.Index(fields=['instance', 'gauge_name'], name='application_instanc_ceb657_idx')],
                'unique_together': {('instance', 'gauge_name')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('user_action', 'User Action'), ('system_event', 'System Event'), ('business_event', 'Business Event'), ('error_event', 'Error Event'), ('custom_event', 'Custom Event')], max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='appmetrics.applicationinstance')),
            ],
            options={
                'db_table': 'application_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instance', 'event_name', 'timestamp'], name='application_instanc_7c0459_idx'), models.Index(fields=['event_type', 'severity', 'timestamp'], name='application_event_t_e6d6f0_idx'), models.Index(fields=['user_id', 'timestamp'], name='application_user_id_b6a5a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('counter_name', models.CharField(db_index=True, max_length=255)),
                ('counter_value', models.BigIntegerField(default=0)),
                ('increment_value', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='appmetrics.applicationinstance')),
            ],
            options={
                'db_table': 'application_counter',
                'indexes': [models.Index(fields=['instance', 'counter_name'], name='application_instanc_b66db2_idx')],
                'unique_together': {('instance', 'counter_name')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationMetricData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('metric_category', models.CharField(choices=[('performance', 'Performance'), ('resource', 'Resource Usage'), ('business', 'Business Logic'), ('error', 'Error Tracking'), ('custom', 'Custom Metric')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('tags', models.JSONField(default=dict, help_text='Additional metric tags')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='appmetrics.applicationinstance')),
            ],
            options={
                'db_table': 'application_metric_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instance', 'metric_name', 'timestamp'], name='application_instanc_014315_idx'), models.Index(fields=['metric_category', 'timestamp'], name='application_metric__61347d_idx')],
            },
        ),
    ]
