# Generated by Django 6.0.1 on 2026-02-01 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='User-defined name for the dashboard', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the dashboard')),
                ('template_version', models.CharField(blank=True, help_text='Version of template used to create this dashboard', max_length=20)),
                ('configuration', models.JSONField(default=dict, help_text='Complete dashboard configuration including layout and widgets')),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this dashboard is shared with other users')),
                ('is_favorite', models.BooleanField(default=False, help_text='Whether this is marked as a favorite dashboard')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default dashboard")),
                ('last_accessed', models.DateTimeField(blank=True, help_text='When this dashboard was last accessed', null=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this dashboard has been accessed')),
                ('owner', models.ForeignKey(help_text='User who owns this dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_dashboards_dashboard',
                'ordering': ['-last_accessed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit Dashboard'), ('admin', 'Full Admin')], default='view', help_text='Permission level for shared dashboard', max_length=20)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='template_dashboards.dashboard')),
                ('shared_by', models.ForeignKey(help_text='User who shared the dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='shared_dashboards_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_dashboards_dashboard_share',
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Users who have access to this dashboard', related_name='accessible_dashboards', through='template_dashboards.DashboardShare', through_fields=('dashboard', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DashboardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Human-readable name for the dashboard template', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the template's purpose and contents")),
                ('layout_config', models.JSONField(default=dict, help_text='Layout configuration including grid settings, responsive breakpoints')),
                ('widget_configs', models.JSONField(default=list, help_text='List of widget configurations with types, positions, and data sources')),
                ('version', models.CharField(default='1.0.0', help_text='Semantic version number (e.g., 1.0.0, 1.2.3)', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this template is publicly available to all users')),
                ('is_system_template', models.BooleanField(default=False, help_text='Whether this is a system-provided template')),
                ('category', models.CharField(blank=True, choices=[('monitoring', 'System Monitoring'), ('analytics', 'Analytics & BI'), ('security', 'Security Dashboard'), ('performance', 'Performance Metrics'), ('network', 'Network Monitoring'), ('application', 'Application Metrics'), ('custom', 'Custom Dashboard')], help_text='Template category for organization', max_length=100)),
                ('tags', models.JSONField(default=list, help_text='List of tags for template discovery and filtering')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_by', models.ForeignKey(help_text='User who created this template', on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, help_text='Parent template for version tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='template_dashboards.dashboardtemplate')),
            ],
            options={
                'db_table': 'template_dashboards_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this dashboard was created from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_instances', to='template_dashboards.dashboardtemplate'),
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart Widget'), ('metric', 'Metric Display'), ('table', 'Data Table'), ('gauge', 'Gauge/Meter'), ('text', 'Text Widget'), ('alert', 'Alert Status'), ('log', 'Log Viewer'), ('custom', 'Custom Widget')], help_text='Type of widget', max_length=100)),
                ('title', models.CharField(help_text='Widget title displayed to users', max_length=255)),
                ('position_x', models.PositiveIntegerField(default=0, help_text='X position in grid')),
                ('position_y', models.PositiveIntegerField(default=0, help_text='Y position in grid')),
                ('width', models.PositiveIntegerField(default=1, help_text='Widget width in grid units')),
                ('height', models.PositiveIntegerField(default=1, help_text='Widget height in grid units')),
                ('config', models.JSONField(default=dict, help_text='Widget-specific configuration including data sources and display options')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether widget is currently visible')),
                ('refresh_interval', models.PositiveIntegerField(default=30, help_text='Refresh interval in seconds (0 for manual refresh)')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='template_dashboards.dashboard')),
            ],
            options={
                'db_table': 'template_dashboards_widget',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='TemplateShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit Template'), ('admin', 'Full Admin')], default='view', help_text='Permission level for shared template', max_length=20)),
                ('shared_by', models.ForeignKey(help_text='User who shared the template', on_delete=django.db.models.deletion.CASCADE, related_name='shared_templates_by', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='template_dashboards.dashboardtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_dashboards_share',
            },
        ),
        migrations.AddField(
            model_name='dashboardtemplate',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Users who have access to this template', related_name='shared_templates', through='template_dashboards.TemplateShare', through_fields=('template', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dashboardshare',
            index=models.Index(fields=['dashboard', 'user'], name='template_da_dashboa_00a7f0_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardshare',
            index=models.Index(fields=['user', 'permission_level'], name='template_da_user_id_355246_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardshare',
            unique_together={('dashboard', 'user')},
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['owner'], name='template_da_owner_i_ae662a_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['template'], name='template_da_templat_f892ab_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_shared'], name='template_da_is_shar_cf62b2_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_favorite'], name='template_da_is_favo_2c8f84_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_default'], name='template_da_is_defa_6650fe_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['last_accessed'], name='template_da_last_ac_039094_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('name', 'owner')},
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['dashboard'], name='template_da_dashboa_90071e_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['widget_type'], name='template_da_widget__36a801_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['position_x', 'position_y'], name='template_da_positio_404dfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidget',
            unique_together={('dashboard', 'position_x', 'position_y')},
        ),
        migrations.AddIndex(
            model_name='templateshare',
            index=models.Index(fields=['template', 'user'], name='template_da_templat_76c67d_idx'),
        ),
        migrations.AddIndex(
            model_name='templateshare',
            index=models.Index(fields=['user', 'permission_level'], name='template_da_user_id_d49508_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateshare',
            unique_together={('template', 'user')},
        ),
        migrations.AddIndex(
            model_name='dashboardtemplate',
            index=models.Index(fields=['name'], name='template_da_name_34ca40_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardtemplate',
            index=models.Index(fields=['category'], name='template_da_categor_eeabf8_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardtemplate',
            index=models.Index(fields=['is_public'], name='template_da_is_publ_5da0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardtemplate',
            index=models.Index(fields=['created_by'], name='template_da_created_5dfd43_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardtemplate',
            index=models.Index(fields=['version'], name='template_da_version_d33b03_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardtemplate',
            index=models.Index(fields=['usage_count'], name='template_da_usage_c_759bdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardtemplate',
            unique_together={('name', 'version', 'created_by')},
        ),
    ]
