# Generated by Django 6.0.1 on 2026-02-01 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('web_service', 'Web Service'), ('api_service', 'API Service'), ('background_service', 'Background Service'), ('database_service', 'Database Service'), ('cache_service', 'Cache Service'), ('message_queue', 'Message Queue')], max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=50)),
                ('health_check_url', models.URLField(blank=True)),
                ('is_monitored', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'application_service',
                'indexes': [models.Index(fields=['service_type', 'environment'], name='application_service_2677b1_idx'), models.Index(fields=['is_monitored'], name='application_is_moni_f55a25_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('metric_type', models.CharField(choices=[('response_time', 'Response Time'), ('throughput', 'Throughput'), ('error_rate', 'Error Rate'), ('cpu_usage', 'CPU Usage'), ('memory_usage', 'Memory Usage'), ('disk_usage', 'Disk Usage'), ('network_io', 'Network I/O'), ('database_connections', 'Database Connections'), ('custom', 'Custom Metric')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=20)),
                ('tags', models.JSONField(default=dict, help_text='Additional metric tags')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='application_performance_monitoring.applicationservice')),
            ],
            options={
                'db_table': 'application_metric',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service', 'metric_name', 'timestamp'], name='application_service_b42299_idx'), models.Index(fields=['metric_type', 'timestamp'], name='application_metric__7d6b95_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationHealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('unknown', 'Unknown')], max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict, help_text='Additional health check details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='application_performance_monitoring.applicationservice')),
            ],
            options={
                'db_table': 'application_health_check',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service', 'status', 'timestamp'], name='application_service_c2b38f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('error_type', models.CharField(db_index=True, max_length=100)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='application_performance_monitoring.applicationservice')),
            ],
            options={
                'db_table': 'application_error',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['service', 'error_type'], name='application_service_3def6a_idx'), models.Index(fields=['severity', 'is_resolved'], name='application_severit_b5e2b7_idx'), models.Index(fields=['last_seen'], name='application_last_se_0ed612_idx')],
            },
        ),
    ]
