# Generated by Django 6.0.1 on 2026-02-01 08:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_type', models.CharField(choices=[('query_execution', 'Query Execution'), ('data_ingestion', 'Data Ingestion'), ('aggregation', 'Data Aggregation'), ('insight_generation', 'Insight Generation'), ('report_generation', 'Report Generation'), ('dashboard_rendering', 'Dashboard Rendering')], max_length=50)),
                ('operation_name', models.CharField(db_index=True, max_length=255)),
                ('execution_time_ms', models.PositiveIntegerField(help_text='Execution time in milliseconds')),
                ('memory_usage_mb', models.FloatField(blank=True, help_text='Memory usage in MB', null=True)),
                ('cpu_usage_percent', models.FloatField(blank=True, help_text='CPU usage percentage', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('data_volume_mb', models.FloatField(blank=True, help_text='Data volume processed in MB', null=True)),
                ('record_count', models.PositiveIntegerField(blank=True, help_text='Number of records processed', null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional performance metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'analytics_performance_metric',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['operation_type', 'timestamp'], name='analytics_p_operati_9d5114_idx'), models.Index(fields=['operation_name', 'success'], name='analytics_p_operati_eabf00_idx'), models.Index(fields=['execution_time_ms'], name='analytics_p_executi_749da0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsResourceUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resource_type', models.CharField(choices=[('cpu', 'CPU'), ('memory', 'Memory'), ('disk_io', 'Disk I/O'), ('network_io', 'Network I/O'), ('database_connections', 'Database Connections')], max_length=50)),
                ('current_usage', models.FloatField()),
                ('peak_usage', models.FloatField()),
                ('average_usage', models.FloatField()),
                ('usage_unit', models.CharField(help_text='Unit of measurement (%, MB, ops/sec, etc.)', max_length=20)),
                ('threshold_warning', models.FloatField(blank=True, null=True)),
                ('threshold_critical', models.FloatField(blank=True, null=True)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('measurement_window_minutes', models.PositiveIntegerField(default=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'analytics_resource_usage',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resource_type', 'timestamp'], name='analytics_r_resourc_66857e_idx'), models.Index(fields=['alert_triggered', 'timestamp'], name='analytics_r_alert_t_e7569b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsPerformanceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('slow_query', 'Slow Query'), ('high_resource_usage', 'High Resource Usage'), ('failed_operation', 'Failed Operation'), ('performance_degradation', 'Performance Degradation')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metric_name', models.CharField(max_length=255)),
                ('threshold_value', models.FloatField()),
                ('actual_value', models.FloatField()),
                ('operation_details', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_performance_alert',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['alert_type', 'severity'], name='analytics_p_alert_t_ff159d_idx'), models.Index(fields=['is_resolved', 'timestamp'], name='analytics_p_is_reso_25dccc_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsQueryPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('query_id', models.CharField(db_index=True, help_text='Query identifier or hash', max_length=255)),
                ('query_type', models.CharField(choices=[('adhoc', 'Ad-hoc Query'), ('scheduled', 'Scheduled Query'), ('dashboard', 'Dashboard Query'), ('alert', 'Alert Query')], max_length=50)),
                ('data_source_count', models.PositiveIntegerField(default=1)),
                ('time_range_hours', models.FloatField(help_text='Time range of query in hours')),
                ('execution_time_ms', models.PositiveIntegerField()),
                ('planning_time_ms', models.PositiveIntegerField(default=0)),
                ('data_scan_mb', models.FloatField(help_text='Amount of data scanned in MB')),
                ('result_size_mb', models.FloatField(help_text='Size of query results in MB')),
                ('cache_hit', models.BooleanField(default=False)),
                ('optimization_applied', models.JSONField(default=list, help_text='List of optimizations applied')),
                ('performance_score', models.FloatField(help_text='Performance score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_query_performance',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['query_type', 'timestamp'], name='analytics_q_query_t_970166_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_q_user_id_1b4c39_idx'), models.Index(fields=['performance_score'], name='analytics_q_perform_54c475_idx'), models.Index(fields=['cache_hit', 'execution_time_ms'], name='analytics_q_cache_h_85cb6f_idx')],
            },
        ),
    ]
