# Generated by Django 6.0.1 on 2026-02-01 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProviderMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_name', models.CharField(db_index=True, max_length=50)),
                ('metric_type', models.CharField(choices=[('auth_response_time', 'Authentication Response Time'), ('token_validation_time', 'Token Validation Time'), ('user_info_fetch_time', 'User Info Fetch Time'), ('auth_success_rate', 'Authentication Success Rate'), ('token_refresh_time', 'Token Refresh Time')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'identity_provider_metric',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['provider_name', 'metric_type', 'timestamp'], name='identity_pr_provide_b4354b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('login_attempt', 'Login Attempt'), ('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('session_timeout', 'Session Timeout')], max_length=50)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authentication_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['provider_name', 'event_type', 'timestamp'], name='authenticat_provide_edb875_idx'), models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_f41198_idx')],
            },
        ),
    ]
