# Generated by Django 6.0.1 on 2026-02-01 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Configuration Categories',
                'db_table': 'settings_configuration_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('regex', 'Regular Expression'), ('range', 'Numeric Range'), ('length', 'String Length'), ('custom', 'Custom Function'), ('dependency', 'Setting Dependency')], max_length=50)),
                ('rule_config', models.JSONField()),
                ('error_message', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'settings_configuration_validation_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_configuration_profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON Object'), ('list', 'List'), ('password', 'Password'), ('url', 'URL'), ('email', 'Email'), ('choice', 'Choice')], max_length=20)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('current_value', models.JSONField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='settings.configurationcategory')),
            ],
            options={
                'db_table': 'settings_configuration_setting',
                'ordering': ['category__sort_order', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationProfileSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.JSONField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to='settings.configurationprofile')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_values', to='settings.configurationsetting')),
            ],
            options={
                'db_table': 'settings_configuration_profile_setting',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='settings.configurationsetting')),
            ],
            options={
                'db_table': 'settings_configuration_change_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('deployment_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rollback_deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollbacks', to='settings.configurationdeployment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='settings.configurationprofile')),
            ],
            options={
                'db_table': 'settings_configuration_deployment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='settings_co_profile_a88a38_idx'), models.Index(fields=['status', '-created_at'], name='settings_co_status_fffd55_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='configurationsetting',
            index=models.Index(fields=['key'], name='settings_co_key_945fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationsetting',
            index=models.Index(fields=['category', 'sort_order'], name='settings_co_categor_7477aa_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationprofilesetting',
            index=models.Index(fields=['profile', 'setting'], name='settings_co_profile_c744af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationprofilesetting',
            unique_together={('profile', 'setting')},
        ),
        migrations.AddIndex(
            model_name='configurationchangelog',
            index=models.Index(fields=['setting', '-created_at'], name='settings_co_setting_bd6b81_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationchangelog',
            index=models.Index(fields=['changed_by', '-created_at'], name='settings_co_changed_ce0787_idx'),
        ),
    ]
