# Generated by Django 6.0.1 on 2026-02-01 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('connector_type', models.CharField(choices=[('pull', 'Pull Data (Import)'), ('push', 'Push Data (Export)'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('data_format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV'), ('yaml', 'YAML'), ('binary', 'Binary'), ('custom', 'Custom Format')], default='json', max_length=20)),
                ('source_endpoint', models.CharField(blank=True, max_length=500)),
                ('destination_endpoint', models.CharField(blank=True, max_length=500)),
                ('sync_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('continuous', 'Continuous'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('sync_schedule', models.JSONField(default=dict, help_text='Cron-like schedule configuration')),
                ('transformation_rules', models.JSONField(default=list, help_text='Data transformation and mapping rules')),
                ('validation_rules', models.JSONField(default=list, help_text='Data validation rules')),
                ('filters', models.JSONField(default=dict, help_text='Data filtering criteria')),
                ('batch_size', models.PositiveIntegerField(default=1000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='pending', max_length=20)),
                ('last_sync_message', models.TextField(blank=True)),
                ('total_records_processed', models.BigIntegerField(default=0)),
                ('total_errors', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'integration_data_connector',
            },
        ),
        migrations.CreateModel(
            name='DataImportExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_type', models.CharField(choices=[('import', 'Data Import'), ('export', 'Data Export'), ('sync', 'Data Synchronization')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('job_config', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
                ('records_processed', models.BigIntegerField(default=0)),
                ('records_successful', models.BigIntegerField(default=0)),
                ('records_failed', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='integration.dataconnector')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration_data_import_export_job',
            },
        ),
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('system_type', models.CharField(choices=[('api', 'REST API'), ('database', 'Database'), ('monitoring', 'Monitoring System'), ('logging', 'Logging System'), ('metrics', 'Metrics System'), ('alerting', 'Alerting System'), ('webhook', 'Webhook'), ('file_system', 'File System'), ('cloud_service', 'Cloud Service'), ('custom', 'Custom Integration')], max_length=50)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Authentication'), ('oauth2', 'OAuth 2.0'), ('custom', 'Custom Authentication')], default='none', max_length=50)),
                ('auth_config', models.JSONField(default=dict, help_text='Authentication configuration (encrypted)')),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('retry_attempts', models.PositiveIntegerField(default=3)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=5)),
                ('health_check_url', models.URLField(blank=True, null=True)),
                ('health_check_interval_minutes', models.PositiveIntegerField(default=5)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('configuration', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_systems', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_external_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration_external_system',
            },
        ),
        migrations.AddField(
            model_name='dataconnector',
            name='external_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='integration.externalsystem'),
        ),
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('endpoint_type', models.CharField(choices=[('webhook', 'Webhook Receiver'), ('api', 'REST API Endpoint'), ('graphql', 'GraphQL Endpoint'), ('websocket', 'WebSocket Endpoint')], max_length=20)),
                ('path', models.CharField(max_length=500)),
                ('http_methods', models.JSONField(default=list, help_text='Allowed HTTP methods')),
                ('version', models.CharField(default='v1', max_length=20)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('deprecation_date', models.DateTimeField(blank=True, null=True)),
                ('requires_authentication', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('request_schema', models.JSONField(default=dict, help_text='JSON schema for request validation')),
                ('response_schema', models.JSONField(default=dict, help_text='JSON schema for response format')),
                ('is_enabled', models.BooleanField(default=True)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('total_errors', models.BigIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('allowed_systems', models.ManyToManyField(blank=True, related_name='allowed_endpoints', to='integration.externalsystem')),
                ('replacement_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.integrationendpoint')),
            ],
            options={
                'db_table': 'integration_endpoint',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('activity_type', models.CharField(choices=[('connection', 'Connection'), ('data_transfer', 'Data Transfer'), ('authentication', 'Authentication'), ('validation', 'Validation'), ('transformation', 'Transformation'), ('error', 'Error'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integration.dataconnector')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integration.integrationendpoint')),
                ('external_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integration.externalsystem')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integration.dataimportexportjob')),
            ],
            options={
                'db_table': 'integration_log',
            },
        ),
        migrations.CreateModel(
            name='ServiceDiscovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('presentation', 'Presentation Layer'), ('logic', 'Logic Layer'), ('data', 'Data Layer'), ('external', 'External Service')], max_length=20)),
                ('instance_id', models.CharField(max_length=255, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(default='http', max_length=10)),
                ('base_path', models.CharField(default='/', max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('environment', models.CharField(default='development', max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('availability_zone', models.CharField(blank=True, max_length=100)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('unknown', 'Unknown'), ('maintenance', 'Maintenance')], default='unknown', max_length=20)),
                ('health_check_url', models.CharField(blank=True, max_length=500)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('max_connections', models.PositiveIntegerField(default=1000)),
                ('current_connections', models.PositiveIntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integration_service_discovery',
                'indexes': [models.Index(fields=['service_name', 'health_status'], name='integration_service_9e943c_idx'), models.Index(fields=['service_type', 'environment'], name='integration_service_96ad58_idx'), models.Index(fields=['last_heartbeat'], name='integration_last_he_ce6ee6_idx')],
                'unique_together': {('service_name', 'instance_id')},
            },
        ),
        migrations.AddIndex(
            model_name='dataimportexportjob',
            index=models.Index(fields=['status', 'started_at'], name='integration_status_8bbbd7_idx'),
        ),
        migrations.AddIndex(
            model_name='dataimportexportjob',
            index=models.Index(fields=['connector', 'job_type', 'status'], name='integration_connect_57e9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='dataimportexportjob',
            index=models.Index(fields=['started_at', 'completed_at'], name='integration_started_b7b07d_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsystem',
            index=models.Index(fields=['system_type', 'is_active'], name='integration_system__45b4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsystem',
            index=models.Index(fields=['is_healthy', 'last_health_check'], name='integration_is_heal_928ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconnector',
            index=models.Index(fields=['connector_type', 'is_enabled'], name='integration_connect_37e15d_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconnector',
            index=models.Index(fields=['sync_frequency', 'last_sync'], name='integration_sync_fr_40b471_idx'),
        ),
        migrations.AddIndex(
            model_name='dataconnector',
            index=models.Index(fields=['external_system', 'is_enabled'], name='integration_externa_27326d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataconnector',
            unique_together={('external_system', 'name')},
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['endpoint_type', 'is_enabled'], name='integration_endpoin_e701fc_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['version', 'is_deprecated'], name='integration_version_2e0a9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationendpoint',
            unique_together={('path', 'version')},
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['level', 'created_at'], name='integration_level_3a87c9_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['activity_type', 'created_at'], name='integration_activit_8c981a_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['external_system', 'created_at'], name='integration_externa_0ceefb_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['request_id'], name='integration_request_75ab10_idx'),
        ),
    ]
