# Generated by Django 6.0.1 on 2026-02-01 08:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('internal', 'Internal System'), ('api', 'External API'), ('file', 'File Upload'), ('database', 'Database Connection'), ('stream', 'Real-time Stream')], max_length=50)),
                ('connection_config', models.JSONField(default=dict, help_text='Configuration for connecting to the data source')),
                ('schema_definition', models.JSONField(default=dict, help_text='Schema definition for data validation')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('minute', 'Every Minute'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual')], default='hourly', max_length=20)),
            ],
            options={
                'db_table': 'analytics_data_source',
                'indexes': [models.Index(fields=['source_type', 'is_enabled'], name='analytics_d_source__325836_idx'), models.Index(fields=['last_sync'], name='analytics_d_last_sy_13d2f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('query_definition', models.JSONField(help_text='Query definition including filters, aggregations, and grouping')),
                ('is_public', models.BooleanField(default=False)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('average_execution_time', models.FloatField(blank=True, help_text='Average execution time in seconds', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_queries', to=settings.AUTH_USER_MODEL)),
                ('data_sources', models.ManyToManyField(related_name='queries', to='analytics.datasource')),
            ],
            options={
                'db_table': 'analytics_query',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('insight_type', models.CharField(choices=[('anomaly', 'Anomaly Detection'), ('trend', 'Trend Analysis'), ('correlation', 'Correlation Analysis'), ('forecast', 'Forecast'), ('recommendation', 'Recommendation')], max_length=50)),
                ('metric_names', models.JSONField(default=list, help_text='List of metric names')),
                ('confidence_score', models.FloatField(help_text='Confidence score between 0 and 1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('impact_score', models.FloatField(help_text='Impact score between 0 and 1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('time_range', models.JSONField(help_text='Time range for the insight')),
                ('analysis_data', models.JSONField(default=dict, help_text='Detailed analysis data and evidence')),
                ('recommendations', models.JSONField(default=list, help_text='Actionable recommendations')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_insights', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analytics.datasource')),
            ],
            options={
                'db_table': 'analytics_insight',
                'ordering': ['-confidence_score', '-impact_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('summary', 'Summary'), ('event', 'Event')], max_length=50)),
                ('metric_value', models.JSONField(help_text='Flexible storage for metric values')),
                ('dimensions', models.JSONField(default=dict, help_text='Dimensional data for grouping and filtering')),
                ('tags', models.JSONField(default=dict, help_text='Additional metadata tags')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('numeric_value', models.FloatField(blank=True, db_index=True, help_text='Extracted numeric value for aggregations', null=True)),
                ('string_value', models.CharField(blank=True, db_index=True, help_text='Extracted string value for grouping', max_length=500)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_data', to='analytics.datasource')),
            ],
            options={
                'db_table': 'analytics_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsAggregation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('aggregation_type', models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum'), ('count', 'Count'), ('stddev', 'Standard Deviation'), ('percentile', 'Percentile')], max_length=20)),
                ('time_window', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('6h', '6 Hours'), ('1d', '1 Day'), ('1w', '1 Week'), ('1M', '1 Month')], max_length=20)),
                ('dimensions', models.JSONField(default=dict, help_text='Grouping dimensions')),
                ('aggregated_value', models.FloatField()),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField(db_index=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregations', to='analytics.datasource')),
            ],
            options={
                'db_table': 'analytics_aggregation',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout_config', models.JSONField(default=dict, help_text='Dashboard layout configuration')),
                ('widgets', models.JSONField(default=list, help_text='Dashboard widgets configuration')),
                ('filters', models.JSONField(default=dict, help_text='Global dashboard filters')),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='Refresh interval in seconds')),
                ('is_public', models.BooleanField(default=False)),
                ('is_realtime', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_dashboards', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_dashboard',
                'indexes': [models.Index(fields=['created_by', 'is_public'], name='analytics_d_created_0c26af_idx'), models.Index(fields=['last_viewed'], name='analytics_d_last_vi_c119fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('condition', models.JSONField(help_text='Alert condition definition')),
                ('threshold_value', models.FloatField()),
                ('comparison_operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('eq', 'Equal'), ('ne', 'Not Equal')], max_length=10)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('notification_channels', models.JSONField(default=list, help_text='Notification channels configuration')),
                ('is_enabled', models.BooleanField(default=True)),
                ('check_frequency', models.PositiveIntegerField(default=300, help_text='Check frequency in seconds')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_alerts', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.analyticsquery')),
            ],
            options={
                'db_table': 'analytics_alert',
                'indexes': [models.Index(fields=['is_enabled', 'last_checked'], name='analytics_a_is_enab_74426e_idx'), models.Index(fields=['severity', 'last_triggered'], name='analytics_a_severit_e6035a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('trend', 'Trend Analysis'), ('comparison', 'Comparison Report'), ('custom', 'Custom Report')], max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Report parameters and filters')),
                ('results', models.JSONField(default=dict, help_text='Cached report results')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Generation time in seconds', null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_config', models.JSONField(default=dict, help_text='Scheduling configuration')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analytics.analyticsquery')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_report',
                'indexes': [models.Index(fields=['created_by', 'report_type'], name='analytics_r_created_540cd8_idx'), models.Index(fields=['generated_at'], name='analytics_r_generat_92794f_idx'), models.Index(fields=['is_scheduled'], name='analytics_r_is_sche_a10610_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='analyticsquery',
            index=models.Index(fields=['created_by', 'is_public'], name='analytics_q_created_905922_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsquery',
            index=models.Index(fields=['last_executed'], name='analytics_q_last_ex_09115e_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsinsight',
            index=models.Index(fields=['insight_type', 'confidence_score'], name='analytics_i_insight_dedf75_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsinsight',
            index=models.Index(fields=['is_acknowledged', 'created_at'], name='analytics_i_is_ackn_5678d3_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdata',
            index=models.Index(fields=['data_source', 'metric_name', 'timestamp'], name='analytics_d_data_so_f1c4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdata',
            index=models.Index(fields=['metric_type', 'timestamp'], name='analytics_d_metric__262d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdata',
            index=models.Index(fields=['timestamp', 'numeric_value'], name='analytics_d_timesta_15f1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdata',
            index=models.Index(fields=['metric_name', 'string_value'], name='analytics_d_metric__6c014f_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsaggregation',
            index=models.Index(fields=['data_source', 'metric_name', 'time_window', 'window_start'], name='analytics_a_data_so_ede8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsaggregation',
            index=models.Index(fields=['aggregation_type', 'window_start'], name='analytics_a_aggrega_4c647d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsaggregation',
            unique_together={('data_source', 'metric_name', 'aggregation_type', 'time_window', 'dimensions', 'window_start')},
        ),
    ]
