# Generated by Django 6.0.1 on 2026-02-01 08:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(help_text='Complex alert conditions with multiple criteria')),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('evaluation_window_minutes', models.PositiveIntegerField(default=5, help_text='Time window for evaluating conditions', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('tags', models.JSONField(default=dict, help_text='Key-value tags for categorization')),
                ('escalation_policy', models.JSONField(default=dict, help_text='Escalation rules for unacknowledged alerts')),
                ('notification_schedule', models.JSONField(default=dict, help_text='Schedule for when notifications should be sent')),
                ('deduplication_window_minutes', models.PositiveIntegerField(default=60, help_text='Time window for deduplicating similar alerts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('deduplication_fields', models.JSONField(default=list, help_text='Fields to use for alert deduplication')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_alert_rule',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fingerprint', models.CharField(help_text='Unique fingerprint for deduplication', max_length=64)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Additional alert context and data')),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='triggered', max_length=20)),
                ('escalation_level', models.PositiveIntegerField(default=0)),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='notification.alertrule')),
            ],
            options={
                'db_table': 'notification_alert',
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Human-readable name for this channel', max_length=100)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('pagerduty', 'PagerDuty')], max_length=50)),
                ('configuration', models.JSONField(help_text='Channel-specific configuration (e.g., email addresses, webhook URLs, API keys)')),
                ('is_enabled', models.BooleanField(default=True)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=100, help_text='Maximum notifications per hour for this channel', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('max_retries', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('retry_delay_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(3600)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_channel',
            },
        ),
        migrations.CreateModel(
            name='AlertRuleNotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='Delay before sending notification through this channel', validators=[django.core.validators.MaxValueValidator(1440)])),
                ('is_escalation', models.BooleanField(default=False, help_text='Whether this channel is part of escalation policy')),
                ('escalation_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.alertrule')),
                ('notification_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationchannel')),
            ],
            options={
                'db_table': 'notification_alert_rule_channel',
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='notification_channels',
            field=models.ManyToManyField(related_name='alert_rules', through='notification.AlertRuleNotificationChannel', to='notification.notificationchannel'),
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.CharField(help_text='Actual recipient (email, phone, etc.)', max_length=255)),
                ('message_content', models.TextField()),
                ('response_data', models.JSONField(default=dict, help_text='Response from delivery service')),
                ('error_message', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notification.alert')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationchannel')),
            ],
            options={
                'db_table': 'notification_delivery',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('alert_triggered', 'Alert Triggered'), ('alert_acknowledged', 'Alert Acknowledged'), ('alert_resolved', 'Alert Resolved'), ('alert_escalated', 'Alert Escalated')], max_length=50)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('pagerduty', 'PagerDuty')], max_length=50)),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('body_template', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_template',
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['rule', 'status'], name='notificatio_rule_id_c10bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['fingerprint', 'status'], name='notificatio_fingerp_609b26_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['triggered_at', 'status'], name='notificatio_trigger_e91ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'escalation_level'], name='notificatio_status_6c25db_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['channel_type', 'is_enabled'], name='notificatio_channel_769d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['created_by'], name='notificatio_created_c28ea9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationchannel',
            unique_together={('name', 'created_by')},
        ),
        migrations.AddIndex(
            model_name='alertrulenotificationchannel',
            index=models.Index(fields=['alert_rule', 'escalation_level'], name='notificatio_alert_r_d913dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertrulenotificationchannel',
            unique_together={('alert_rule', 'notification_channel')},
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['is_enabled', 'severity'], name='notificatio_is_enab_73f963_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['created_by'], name='notificatio_created_b22af1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['alert', 'channel'], name='notificatio_alert_i_ef1ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_15366f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_2e8ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['template_type', 'channel_type'], name='notificatio_templat_6bdb90_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_default'], name='notificatio_is_defa_d72370_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('template_type', 'channel_type', 'is_default')},
        ),
    ]
