# Generated by Django 6.0.1 on 2026-02-01 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('framework', models.CharField(choices=[('gdpr', 'GDPR'), ('hipaa', 'HIPAA'), ('pci_dss', 'PCI DSS'), ('sox', 'SOX'), ('iso27001', 'ISO 27001'), ('nist', 'NIST'), ('cis', 'CIS Controls'), ('custom', 'Custom Framework')], max_length=50)),
                ('control_id', models.CharField(max_length=100)),
                ('control_name', models.CharField(max_length=255)),
                ('requirement_description', models.TextField()),
                ('implementation_status', models.CharField(choices=[('not_implemented', 'Not Implemented'), ('partially_implemented', 'Partially Implemented'), ('implemented', 'Implemented'), ('not_applicable', 'Not Applicable')], max_length=25)),
                ('compliance_score', models.FloatField(blank=True, help_text='Compliance score (0.0 to 100.0)', null=True)),
                ('evidence', models.TextField(blank=True)),
                ('responsible_party', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_assessment', models.DateTimeField(auto_now=True)),
                ('next_assessment', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compliance_check',
                'indexes': [models.Index(fields=['framework', 'implementation_status'], name='compliance__framewo_f278c1_idx'), models.Index(fields=['due_date', 'implementation_status'], name='compliance__due_dat_27f755_idx')],
                'unique_together': {('framework', 'control_id')},
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('authentication_failure', 'Authentication Failure'), ('authorization_failure', 'Authorization Failure'), ('brute_force_attempt', 'Brute Force Attempt'), ('suspicious_activity', 'Suspicious Activity'), ('malware_detection', 'Malware Detection'), ('intrusion_attempt', 'Intrusion Attempt'), ('data_breach', 'Data Breach'), ('vulnerability_exploit', 'Vulnerability Exploit'), ('ddos_attack', 'DDoS Attack'), ('sql_injection', 'SQL Injection'), ('xss_attack', 'XSS Attack'), ('csrf_attack', 'CSRF Attack')], db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('target_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('payload', models.TextField(blank=True)),
                ('detection_method', models.CharField(choices=[('signature', 'Signature-based'), ('anomaly', 'Anomaly-based'), ('behavioral', 'Behavioral Analysis'), ('machine_learning', 'Machine Learning'), ('rule_based', 'Rule-based')], max_length=50)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score (0.0 to 1.0)', null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('response_action', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block'), ('quarantine', 'Quarantine'), ('alert', 'Alert Only'), ('monitor', 'Monitor')], default='alert', max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'security_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'severity', 'timestamp'], name='security_ev_event_t_1c94f5_idx'), models.Index(fields=['source_ip', 'timestamp'], name='security_ev_source__516c9f_idx'), models.Index(fields=['is_blocked', 'is_false_positive'], name='security_ev_is_bloc_f191fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityMetricData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('metric_category', models.CharField(choices=[('threat_detection', 'Threat Detection'), ('incident_response', 'Incident Response'), ('vulnerability_management', 'Vulnerability Management'), ('access_control', 'Access Control'), ('compliance', 'Compliance'), ('security_awareness', 'Security Awareness')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('threshold_warning', models.FloatField(blank=True, null=True)),
                ('threshold_critical', models.FloatField(blank=True, null=True)),
                ('is_kpi', models.BooleanField(default=False, help_text='Key Performance Indicator')),
                ('tags', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'security_metric_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', 'metric_category', 'timestamp'], name='security_me_metric__0d11bb_idx'), models.Index(fields=['is_kpi', 'timestamp'], name='security_me_is_kpi_c6b640_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator_type', models.CharField(choices=[('ip_address', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('file_hash', 'File Hash'), ('email', 'Email Address'), ('user_agent', 'User Agent'), ('certificate', 'Certificate')], max_length=50)),
                ('indicator_value', models.CharField(db_index=True, max_length=500)),
                ('threat_type', models.CharField(choices=[('malware', 'Malware'), ('botnet', 'Botnet'), ('phishing', 'Phishing'), ('spam', 'Spam'), ('tor_exit_node', 'Tor Exit Node'), ('proxy', 'Proxy/VPN'), ('scanner', 'Scanner'), ('brute_force', 'Brute Force'), ('ddos', 'DDoS'), ('apt', 'Advanced Persistent Threat')], max_length=100)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('confirmed', 'Confirmed')], max_length=20)),
                ('source', models.CharField(help_text='Intelligence source', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'threat_intelligence',
                'indexes': [models.Index(fields=['indicator_type', 'indicator_value'], name='threat_inte_indicat_661a97_idx'), models.Index(fields=['threat_type', 'confidence_level'], name='threat_inte_threat__b10841_idx'), models.Index(fields=['is_active', 'last_seen'], name='threat_inte_is_acti_24af68_idx')],
                'unique_together': {('indicator_type', 'indicator_value', 'source')},
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_system', models.CharField(db_index=True, max_length=255)),
                ('target_ip', models.GenericIPAddressField()),
                ('vulnerability_id', models.CharField(help_text='CVE ID or custom identifier', max_length=100)),
                ('vulnerability_name', models.CharField(max_length=255)),
                ('severity_score', models.FloatField(help_text='CVSS score or custom severity score')),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('category', models.CharField(choices=[('injection', 'Injection'), ('broken_auth', 'Broken Authentication'), ('sensitive_data', 'Sensitive Data Exposure'), ('xxe', 'XML External Entities'), ('broken_access', 'Broken Access Control'), ('security_misconfig', 'Security Misconfiguration'), ('xss', 'Cross-Site Scripting'), ('insecure_deserialization', 'Insecure Deserialization'), ('known_vulnerabilities', 'Known Vulnerabilities'), ('insufficient_logging', 'Insufficient Logging')], max_length=100)),
                ('description', models.TextField()),
                ('remediation', models.TextField(blank=True)),
                ('affected_service', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('is_exploitable', models.BooleanField(default=False)),
                ('is_patched', models.BooleanField(default=False)),
                ('patch_available', models.BooleanField(default=False)),
                ('discovery_method', models.CharField(choices=[('automated_scan', 'Automated Scan'), ('manual_test', 'Manual Test'), ('penetration_test', 'Penetration Test'), ('code_review', 'Code Review'), ('threat_intel', 'Threat Intelligence')], max_length=50)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vulnerability_assessment',
                'ordering': ['-severity_score', '-scan_date'],
                'indexes': [models.Index(fields=['target_system', 'severity_level'], name='vulnerabili_target__edb43c_idx'), models.Index(fields=['vulnerability_id', 'is_patched'], name='vulnerabili_vulnera_113a9c_idx'), models.Index(fields=['category', 'is_exploitable'], name='vulnerabili_categor_6d8802_idx')],
            },
        ),
    ]
