// Icon utility to handle Lucide Angular icons
import { 
  Check, 
  Minus, 
  X, 
  ChevronDown, 
  ChevronUp, 
  ChevronLeft, 
  ChevronRight,
  RefreshCw,
  Settings,
  Maximize2,
  Loader2,
  Plus,
  User,
  Users,
  DollarSign,
  Clock,
  AlertTriangle,
  AlertCircle,
  CheckCircle,
  XCircle,
  Info,
  Home,
  Edit,
  Copy,
  Trash2,
  PlayCircle,
  Zap,
  Cpu,
  HardDrive,
  BarChart3,
  Eye,
  Search,
  Bell,
  HelpCircle,
  LogOut,
  Shield,
  LayoutDashboard,
  Activity,
  WifiOff,
  Play,
  Pause,
  MoreHorizontal,
  Share,
  MessageCircle,
  Sliders,
  Download,
  Upload,
  Wifi,
  Database,
  Shuffle,
  TrendingUp,
  TrendingDown,
  FileText,
  GitBranch,
  Layers,
  Bug,
  UserX,
  UserCheck,
  Crown,
  History,
  Calendar,
  Send,
  Smartphone,
  Globe,
  Mail,
  Link,
  Share2,
  Server,
  Router,
  Thermometer,
  PieChart,
  Webhook,
  ExternalLink,
  RefreshCw as Refresh,
  MessageSquare
} from 'lucide-angular';

// Export commonly used icons
export const Icons = {
  check: Check,
  minus: Minus,
  x: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  refreshCw: RefreshCw,
  settings: Settings,
  maximize2: Maximize2,
  loader2: Loader2,
  plus: Plus,
  user: User,
  users: Users,
  dollarSign: DollarSign,
  clock: Clock,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  info: Info,
  home: Home,
  edit: Edit,
  copy: Copy,
  trash2: Trash2,
  playCircle: PlayCircle,
  zap: Zap,
  cpu: Cpu,
  hardDrive: HardDrive,
  barChart3: BarChart3,
  eye: Eye,
  search: Search,
  bell: Bell,
  helpCircle: HelpCircle,
  logOut: LogOut,
  shield: Shield,
  layoutDashboard: LayoutDashboard,
  activity: Activity,
  wifiOff: WifiOff,
  play: Play,
  pause: Pause,
  moreHorizontal: MoreHorizontal,
  share: Share,
  messageCircle: MessageCircle,
  sliders: Sliders,
  download: Download,
  upload: Upload,
  wifi: Wifi,
  database: Database,
  shuffle: Shuffle,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  fileText: FileText,
  gitBranch: GitBranch,
  layers: Layers,
  bug: Bug,
  userX: UserX,
  userCheck: UserCheck,
  crown: Crown,
  history: History,
  calendar: Calendar,
  send: Send,
  smartphone: Smartphone,
  globe: Globe,
  mail: Mail,
  link: Link,
  share2: Share2,
  server: Server,
  router: Router,
  thermometer: Thermometer,
  pieChart: PieChart,
  webhook: Webhook,
  externalLink: ExternalLink,
  refresh: Refresh,
  messageSquare: MessageSquare
};

// Type for icon names
export type IconName = keyof typeof Icons;

// Helper function to get icon by name
export function getIcon(name: IconName) {
  return Icons[name];
}